window.addEventListener('error', e => alert('Error: ' + e.message));
const shell=document.getElementById('game'),canvas=document.getElementById('map'),ctx=canvas.getContext('2d');
const layers={routes:document.getElementById('routes'),vehicles:document.getElementById('vehicles'),buildings:document.getElementById('buildings'),fx:document.getElementById('fx')};
const SAVE='economy-complete-v03';
const resources={corn:{icon:'🌽',name:'Maíz',price:2},flour:{icon:'🌾',name:'Harina',price:6},tomato:{icon:'🍅',name:'Tomate',price:3},sauce:{icon:'🥫',name:'Salsa',price:8},milk:{icon:'🥛',name:'Leche',price:4},cheese:{icon:'🧀',name:'Queso',price:10},pizza:{icon:'🍕',name:'Pizza',price:25},bread:{icon:'🍞',name:'Pan',price:12}};
const defs={cornFarm:{name:'Maizal',icon:'🌽',kind:'producer',out:'corn',time:2,cap:20,cost:0,unlock:1},depot:{name:'Depósito',icon:'📦',kind:'storage',cap:100,cost:20,unlock:1},market:{name:'Mercado',icon:'🏪',kind:'market',cost:0,unlock:1},mill:{name:'Molino',icon:'🏭',kind:'factory',in:{corn:2},out:'flour',time:4,cap:40,cost:60,unlock:2},tomatoFarm:{name:'Tomatera',icon:'🍅',kind:'producer',out:'tomato',time:3,cap:20,cost:80,unlock:3},sauce:{name:'Salsas',icon:'🥫',kind:'factory',in:{tomato:2},out:'sauce',time:5,cap:35,cost:120,unlock:4},dairy:{name:'Tambo',icon:'🥛',kind:'producer',out:'milk',time:3.5,cap:20,cost:150,unlock:5},cheese:{name:'Quesería',icon:'🧀',kind:'factory',in:{milk:2},out:'cheese',time:6,cap:35,cost:220,unlock:6},bakery:{name:'Panadería',icon:'🍞',kind:'factory',in:{flour:2},out:'bread',time:5.5,cap:30,cost:260,unlock:7},pizzeria:{name:'Pizzería',icon:'🍕',kind:'factory',in:{flour:1,sauce:1,cheese:1},out:'pizza',time:8,cap:25,cost:400,unlock:8}};
const upgrades={production:{name:'Producción',icon:'⚙️',lvl:0,cost:35,growth:1.22,desc:'Todos producen más rápido.'},transport:{name:'Transporte',icon:'🚚',lvl:0,cost:40,growth:1.24,desc:'Vehículos más veloces y más simultáneos.'},market:{name:'Mercado',icon:'💰',lvl:0,cost:55,growth:1.28,desc:'Vende todo más caro.'},storage:{name:'Almacén',icon:'📦',lvl:0,cost:30,growth:1.2,desc:'Más capacidad general.'}};
const state={money:0,xp:0,level:1,mode:'normal',tiles:[],buildings:[],routes:[],vehicles:[],selected:null,buildType:null,dragging:null,last:performance.now()};
function initNew(){state.tiles=[];[[.30,.36],[.50,.60],[.72,.36],[.20,.48],[.42,.42],[.62,.52],[.82,.50]].forEach((c,i)=>state.tiles.push({id:'t'+i,x:c[0],y:c[1]}));state.buildings=[makeBuilding('cornFarm','t0'),makeBuilding('depot','t1'),makeBuilding('market','t2')];}
function makeBuilding(type,tileId){const tile=state.tiles.find(t=>t.id===tileId);return{id:'b'+Date.now()+Math.random().toString(16).slice(2),type,tileId,x:tile.x,y:tile.y,stock:{},timer:0};}
function load(){const s=localStorage.getItem(SAVE);if(!s){initNew();return}try{const d=JSON.parse(s);Object.assign(state,d);if(d.upgrades)for(const k in upgrades)if(d.upgrades[k]!=null)upgrades[k].lvl=d.upgrades[k];}catch{initNew();}}
function save(){localStorage.setItem(SAVE,JSON.stringify({money:state.money,xp:state.xp,level:state.level,tiles:state.tiles,buildings:state.buildings,routes:state.routes,selected:state.selected,upgrades:Object.fromEntries(Object.entries(upgrades).map(([k,u])=>[k,u.lvl]))}));}
load();
function W(){return shell.clientWidth}function H(){return shell.clientHeight}function pxX(x){return x*W()}function pxY(y){return y*H()}function def(b){return defs[b.type]}function getB(id){return state.buildings.find(b=>b.id===id)}function resIcon(r){return resources[r]?.icon||'📦'}function resName(r){return resources[r]?.name||r}function routesFrom(id){return state.routes.filter(r=>r.from===id)}function multMarket(){return 1+upgrades.market.lvl*.12}function sellPrice(r){return Math.max(1,Math.floor(resources[r].price*multMarket()))}function timeMult(){return Math.max(.28,1-upgrades.production.lvl*.035)}function vehSpeed(){return .30+upgrades.transport.lvl*.018}function vehMax(){return 2+Math.floor(upgrades.transport.lvl/3)}function capMult(){return 1+upgrades.storage.lvl*.25}function capacity(b){const d=def(b);return d.kind==='market'?999999:Math.floor((d.cap||50)*capMult())}function totalStock(b){return Object.values(b.stock||{}).reduce((a,c)=>a+c,0)}function addStock(b,r,n){b.stock[r]=(b.stock[r]||0)+n}function takeStock(b,r,n){if((b.stock[r]||0)<n)return false;b.stock[r]-=n;if(b.stock[r]<=0)delete b.stock[r];return true}function canStore(b,n=1){return totalStock(b)+n<=capacity(b)}function canConsume(b){const d=def(b);return d.in&&Object.entries(d.in).every(([r,n])=>(b.stock[r]||0)>=n)}
function update(dt){for(const b of state.buildings){const d=def(b);b.timer+=dt;if(d.kind==='producer'&&b.timer>=d.time*timeMult()){b.timer=0;dispatchOrStore(b,d.out)}if(d.kind==='factory'&&b.timer>=d.time*timeMult()){b.timer=0;if(canConsume(b)){for(const [r,n]of Object.entries(d.in))takeStock(b,r,n);dispatchOrStore(b,d.out)}}}for(const r of state.routes){const from=getB(r.from);if(from&&def(from).kind==='storage')dispatchAnyStored(from,r)}for(const v of state.vehicles)v.t+=dt*v.speed;const arrived=state.vehicles.filter(v=>v.t>=1);state.vehicles=state.vehicles.filter(v=>v.t<1);for(const v of arrived){const to=getB(v.to);if(!to)continue;if(def(to).kind==='market'){const gain=sellPrice(v.res);state.money+=gain;state.xp+=gain;float('+'+gain+' 🪙',pxX(to.x),pxY(to.y)-75);levelCheck()}else if(canStore(to)){addStock(to,v.res,1);float('+1 '+resIcon(v.res),pxX(to.x),pxY(to.y)-75)}}}
function dispatchOrStore(b,res){const rs=routesFrom(b.id);if(rs.length){const r=rs[0];if(canSend(b.id))state.vehicles.push({from:b.id,to:r.to,res,t:0,speed:vehSpeed()});else if(canStore(b))addStock(b,res,1)}else if(canStore(b)){addStock(b,res,1);float('+1 '+resIcon(res),pxX(b.x),pxY(b.y)-75)}}
function dispatchAnyStored(b,r){if(!canSend(b.id))return;const first=Object.keys(b.stock||{}).find(k=>b.stock[k]>0);if(!first)return;takeStock(b,first,1);state.vehicles.push({from:b.id,to:r.to,res:first,t:0,speed:vehSpeed()})}function canSend(id){return state.vehicles.filter(v=>v.from===id).length<vehMax()}function levelNeed(){return 100+(state.level-1)*65}function levelCheck(){while(state.xp>=levelNeed()){state.xp-=levelNeed();state.level++;toast('Nivel '+state.level+' ⭐');unlockTile()}}function unlockTile(){const n=state.tiles.length,x=.16+((n*37)%68)/100,y=.24+((n*29)%48)/100;state.tiles.push({id:'t'+n,x:Math.min(.86,Math.max(.12,x)),y:Math.min(.72,Math.max(.2,y))})}
function resize(){const dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=W()*dpr;canvas.height=H()*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);drawMap();render()}window.addEventListener('resize',resize);
function drawMap(){ctx.clearRect(0,0,W(),H());const g=ctx.createLinearGradient(0,0,0,H());g.addColorStop(0,'#14bde0');g.addColorStop(1,'#0876a6');ctx.fillStyle=g;ctx.fillRect(0,0,W(),H());for(const t of state.tiles)drawHex(pxX(t.x),pxY(t.y),Math.min(54,W()*.12));['🌲','🌳','🪨','🌼','🌲','🪨'].forEach((ico,i)=>drawText(ico,pxX(.15+((i*19)%70)/100),pxY(.22+((i*13)%48)/100),24))}function drawHex(x,y,r){ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/180*(60*i+30),nx=x+r*Math.cos(a),ny=y+r*Math.sin(a);if(!i)ctx.moveTo(nx,ny);else ctx.lineTo(nx,ny)}ctx.closePath();ctx.fillStyle='#8bd84b';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#477d1fcc';ctx.stroke()}function drawText(t,x,y,s){ctx.font=s+'px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t,x,y)}
function render(){renderHud();renderGoal();renderRoutes();renderBuildings();renderVehicles();renderInfo();renderBuildList();renderUpgradeList()}function renderHud(){money.textContent=state.money;level.textContent=state.level;xp.textContent=state.xp+'/'+levelNeed()}function renderGoal(){const next=Object.entries(defs).find(([k,d])=>d.unlock===state.level+1);goal.textContent=next?`Objetivo: llegá al nivel ${state.level+1} y desbloqueá ${next[1].icon} ${next[1].name}`:`Nivel ${state.level}: expandí, conectá rutas y optimizá tu economía`}
function renderRoutes(){layers.routes.innerHTML='';for(const r of state.routes){const a=getB(r.from),b=getB(r.to);if(a&&b)line(a,b,'route active')}if(state.dragging){const a=getB(state.dragging.from);line({x:a.x,y:a.y},{x:state.dragging.x/W(),y:state.dragging.y/H()},'drag')}}function line(a,b,cls){const x1=pxX(a.x),y1=pxY(a.y)+12,x2=pxX(b.x),y2=pxY(b.y)+12,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy);const el=document.createElement('div');el.className=cls;el.style.left=x1+'px';el.style.top=(y1-(cls==='drag'?3:10))+'px';el.style.width=len+'px';el.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;layers.routes.appendChild(el)}
function renderBuildings(){layers.buildings.innerHTML='';for(const b of state.buildings){const d=def(b),main=d.kind==='market'?`Compra +${Math.floor((multMarket()-1)*100)}%`:stockText(b);const el=document.createElement('div');el.className='building'+(state.selected===b.id?' selected':'');el.dataset.id=b.id;el.style.left=pxX(b.x)+'px';el.style.top=pxY(b.y)+'px';el.innerHTML=`<div class="badge">${d.name}<strong>${main}</strong></div><div class="base"></div><div class="bico">${d.icon}</div>`;el.addEventListener('pointerdown',buildingDown);layers.buildings.appendChild(el)}}function stockText(b){const e=Object.entries(b.stock||{}).filter(x=>x[1]>0);return e.length?e.map(([r,n])=>resIcon(r)+n).join(' ')+' / '+capacity(b):'0 / '+capacity(b)}
function renderVehicles(){layers.vehicles.innerHTML='';for(const v of state.vehicles){const a=getB(v.from),b=getB(v.to);if(!a||!b)continue;const t=smooth(v.t),x=lerp(pxX(a.x),pxX(b.x),t),y=lerp(pxY(a.y)+12,pxY(b.y)+12,t);const el=document.createElement('div');el.className='vehicle';el.style.left=x+'px';el.style.top=y+'px';el.innerHTML=`<span>${resIcon(v.res)}</span>${v.from===state.buildings[0]?.id?'🚜':'🚚'}`;layers.vehicles.appendChild(el)}}
function renderInfo(){const p=info;if(!state.selected){p.classList.add('hidden');return}const b=getB(state.selected);if(!b){p.classList.add('hidden');return}const d=def(b);p.classList.remove('hidden');let html=`<h3>${d.icon} ${d.name}</h3>`;if(d.kind==='producer')html+=`<p>Produce ${resIcon(d.out)} ${resName(d.out)} cada ${(d.time*timeMult()).toFixed(1)}s</p>`;if(d.kind==='factory')html+=`<p>Convierte ${Object.entries(d.in).map(([r,n])=>n+' '+resIcon(r)).join(' + ')} → ${resIcon(d.out)} ${resName(d.out)}</p>`;if(d.kind==='storage')html+=`<p>Guarda y despacha recursos. Capacidad ${capacity(b)}</p>`;if(d.kind==='market')html+=`<p>Vende recursos. Maíz ${sellPrice('corn')} 🪙 / Pizza ${sellPrice('pizza')} 🪙</p>`;html+=`<p>Stock: <b>${stockText(b)}</b></p>`;p.innerHTML=html}
function renderBuildList(){buildList.innerHTML='';Object.entries(defs).filter(([k,d])=>d.cost>0&&d.unlock<=state.level).forEach(([type,d])=>{const can=state.money>=d.cost&&state.tiles.some(t=>!occupied(t.id));const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="ico">${d.icon}</div><div><h4>${d.name}</h4><p>${desc(d)}</p></div><button ${can?'':'disabled'}>${d.cost} 🪙</button>`;card.querySelector('button').onclick=()=>{state.buildType=type;state.mode='build';hideSheets();toast('Tocá un hexágono libre')};buildList.appendChild(card)})}function desc(d){if(d.kind==='producer')return 'Produce '+resName(d.out);if(d.kind==='factory')return 'Crea '+resName(d.out);if(d.kind==='storage')return 'Almacena recursos';return ''}function occupied(tileId){return state.buildings.some(b=>b.tileId===tileId)}
function renderUpgradeList(){upgradeList.innerHTML='';Object.entries(upgrades).forEach(([id,u])=>{const c=Math.floor(u.cost*Math.pow(u.growth,u.lvl)),can=state.money>=c;const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="ico">${u.icon}</div><div><h4>${u.name} Nv.${u.lvl}</h4><p>${u.desc}</p></div><button ${can?'':'disabled'}>${c} 🪙</button>`;card.querySelector('button').onclick=()=>{if(state.money<c)return;state.money-=c;u.lvl++;toast('Mejora: '+u.name);save();render()};upgradeList.appendChild(card)})}
function buildingDown(e){const b=getB(e.currentTarget.dataset.id);state.selected=b.id;if(state.mode==='route'&&def(b).kind!=='market'){state.dragging={from:b.id,x:e.clientX-shell.getBoundingClientRect().left,y:e.clientY-shell.getBoundingClientRect().top};e.currentTarget.setPointerCapture(e.pointerId)}render()}
window.addEventListener('pointermove',e=>{if(!state.dragging)return;const r=shell.getBoundingClientRect();state.dragging.x=e.clientX-r.left;state.dragging.y=e.clientY-r.top;renderRoutes()});window.addEventListener('pointerup',e=>{if(state.dragging){const r=shell.getBoundingClientRect(),target=getBAt(e.clientX-r.left,e.clientY-r.top),from=getB(state.dragging.from);if(target&&target.id!==from.id){state.routes=state.routes.filter(x=>x.from!==from.id);state.routes.push({from:from.id,to:target.id});toast('Ruta creada')}else toast('Ruta no válida');state.dragging=null;save();render();return}if(state.mode==='build'){const r=shell.getBoundingClientRect(),tile=getTileAt(e.clientX-r.left,e.clientY-r.top);if(tile&&!occupied(tile.id)&&state.buildType){const d=defs[state.buildType];if(state.money>=d.cost){state.money-=d.cost;state.buildings.push(makeBuilding(state.buildType,tile.id));state.mode='normal';state.buildType=null;toast('Construido');save();render()}}}});
function getBAt(x,y){return state.buildings.find(b=>Math.hypot(x-pxX(b.x),y-pxY(b.y))<62)}function getTileAt(x,y){return state.tiles.find(t=>Math.hypot(x-pxX(t.x),y-pxY(t.y))<48)}
routeModeBtn.onclick=()=>{state.mode=state.mode==='route'?'normal':'route';routeModeBtn.classList.toggle('active',state.mode==='route');hideSheets();toast(state.mode==='route'?'Modo rutas':'Modo normal')};buildBtn.onclick=()=>toggleSheet('buildPanel');upgradeBtn.onclick=()=>toggleSheet('upgradePanel');expandBtn.onclick=()=>{const cost=50+state.tiles.length*15;if(state.money<cost)return toast('Expandir cuesta '+cost+' 🪙');state.money-=cost;unlockTile();toast('Mapa expandido');save();resize()};resetBtn.onclick=()=>{if(confirm('¿Reiniciar partida?')){localStorage.removeItem(SAVE);location.reload()}};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add('hidden'));
function toggleSheet(id){document.getElementById(id).classList.toggle('hidden');if(id!=='buildPanel')buildPanel.classList.add('hidden');if(id!=='upgradePanel')upgradePanel.classList.add('hidden')}function hideSheets(){buildPanel.classList.add('hidden');upgradePanel.classList.add('hidden')}function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),1100)}function float(t,x,y){const el=document.createElement('div');el.className='float';el.textContent=t;el.style.left=x+'px';el.style.top=y+'px';layers.fx.appendChild(el);setTimeout(()=>el.remove(),1000)}function lerp(a,b,t){return a+(b-a)*t}function smooth(t){return t*t*(3-2*t)}function loop(now){const dt=Math.min((now-state.last)/1000,.05);state.last=now;update(dt);render();requestAnimationFrame(loop)}setInterval(save,8000);resize();render();requestAnimationFrame(loop);
